# Generated by Django 5.1.4 on 2025-01-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_term_options_term_enrollment_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClazzRoom",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, editable=False, null=True)),
                ("updated_by", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "clazz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.clazz"
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Room",
                "verbose_name_plural": "Class Rooms",
                "db_table": "clazz_room",
                "unique_together": {("clazz", "name")},
            },
        ),
    ]
